### ISSUE TITLE
Some graphics ideas

### ISSUE THREAD

**Issue by cormullion** [mfiano/CoherentNoise.jl#4]
Here's an idea for the social media preview (1280 by 640, add it via Settings > General and also link to it in a README perhaps).

![coherent-noise-social-media-preview](https://user-images.githubusercontent.com/52289/185468298-b4a77dd7-3ca4-4336-9c06-33660dc08882.png)

Well, it's all pretty groovy - perhaps a bit too groovy - perhaps way too groovy for you... ? :)  

Edit: changed text

**Comment by mfiano** [comment]
Added to social media preview, README, and documentation front. Thank you!

**Comment by cormullion** [comment]
Cool, thanks! I'll upload the icon tomorrow...

**Comment by mfiano** [comment]
I was wondering what "Some graphics ideas" meant, with one graphic idea :)
